#!/bin/sh
#
# @name Holybro X500 V2
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Yevhenii Kovryzhenko <yzk0058@auburn.edu>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults


# Declare the flag to indicate this is a Simulink-controlled vehicle
set SIM_CTRL_EN true

param set-default IMU_GYRO_CUTOFF 30

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_KM -0.05


# Simulink Guidance Parameters:
param set-default SMG_EN 1
param set-default SMG_OUT_TYPE 2
param set-default SMG_TRAJ_DIR 1

param set-default SDLOG_PROFILE 4097


# Hover Thrust (Crucial for Land Detector)
# Set this to the exact expected hover throttle of your real vehicle (0.0 to 1.0)
#  * @unit norm
#  * @min 0.1
#  * @max 0.8
#  * @decimal 2
#  * @increment 0.01
param set-default MPC_THR_HOVER 0.375

# Data Link Loss Failsafe Action
#  * @value 0 Disabled
#  * @value 1 Hold mode
#  * @value 2 Return mode
#  * @value 3 Land mode
#  * @value 5 Terminate
#  * @value 6 Disarm
param set-default NAV_DLL_ACT 0


# RC Link Loss Failsafe Action
#  * @value 1 Hold mode
#  * @value 2 Return mode
#  * @value 3 Land mode
#  * @value 5 Terminate
#  * @value 6 Disarm
param set-default NAV_RCL_ACT 0


# Force PX4 to execute a full, permanent Flight Termination
# when an emergency kill command is received from the GCS or an RC switch.
# Sets value in seconds to disarm after kill switch/termination is active
param set-default COM_KILL_DISARM 0

