uint64 timestamp          # Time since system start (microseconds)

bool enable               # System loop active
bool hold                 # Alitude/Position input hold active
bool autonomous           # Autonomous trajectory path input active
bool position_xy          # Horizontal position input active
bool position_z           # Vertical position input active
bool rollpitch            # Attitude (roll and pitch) input active
bool yaw                  # Heading input active
bool thrust               # Force input active
bool moment               # Moment input active
