#!/bin/sh
#
# @name Gazebo s500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=s500}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# Simulink Guidance Parameters:
param set-default SMG_EN 1
param set-default SMG_OUT_TYPE 1
param set-default SMG_TRAJ_DIR 0

param set-default SDLOG_PROFILE 4097


# Hover Thrust (Crucial for Land Detector)
# Set this to the exact expected hover throttle of your real vehicle (0.0 to 1.0)
#  * @unit norm
#  * @min 0.1
#  * @max 0.8
#  * @decimal 2
#  * @increment 0.01
param set-default MPC_THR_HOVER 0.375

# Data Link Loss Failsafe Action
#  * @value 0 Disabled
#  * @value 1 Hold mode
#  * @value 2 Return mode
#  * @value 3 Land mode
#  * @value 5 Terminate
#  * @value 6 Disarm
param set-default NAV_DLL_ACT 0


# RC Link Loss Failsafe Action
#  * @value 1 Hold mode
#  * @value 2 Return mode
#  * @value 3 Land mode
#  * @value 5 Terminate
#  * @value 6 Disarm
param set-default NAV_RCL_ACT 0


# Force PX4 to execute a full, permanent Flight Termination
# when an emergency kill command is received from the GCS or an RC switch.
# Sets value in seconds to disarm after kill switch/termination is active
param set-default COM_KILL_DISARM 0
