#!/bin/sh
#
# @name Gazebo s500 with simulink modules
#
# @type Quadrotor
#

. ${R}etc/init.d-posix/airframes/4030_gz_s500

PX4_SIM_MODEL=s500

# Declare the Simulink operation mode
# 0 = Standard stock PX4 behavior (Default if unset)
# 1 = Standard vehicle setup + start Simulink guidance/IO modules at the end
# 2 = Bypass standard setup, run custom apps only (Full Simulink Control)
set SIMULINK_MODE 1

# Simulink Guidance Parameters:
# param set-default SMG_EN 1
# param set-default SMG_OUT_TYPE 1
# param set-default SMG_TRAJ_DIR 0

# param set-default SDLOG_PROFILE 4097
