#!/bin/sh
#
# @name Gazebo s500 with simulink control system
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

# Declare the flag to indicate this is a Simulink-controlled vehicle
set SIM_CTRL_EN true

set PX4_SIM_MODEL s500
PX4_SIM_MODEL=s500

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
# PX4_SIM_MODEL=${PX4_SIM_MODEL:=s500}

param set-default SIM_GZ_EN 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 100
param set-default SIM_GZ_EC_MIN2 100
param set-default SIM_GZ_EC_MIN3 100
param set-default SIM_GZ_EC_MIN4 100

param set-default SIM_GZ_EC_MAX1 1075.4
param set-default SIM_GZ_EC_MAX2 1075.4
param set-default SIM_GZ_EC_MAX3 1075.4
param set-default SIM_GZ_EC_MAX4 1075.4

param set-default MPC_THR_HOVER 0.50
param set-default NAV_DLL_ACT 2




