#!/bin/sh
#
# @name Gazebo s500 with simulink control system
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

# Declare the Simulink operation mode
# 0 = Standard stock PX4 behavior (Default if unset)
# 1 = Standard vehicle setup + start Simulink guidance/IO modules at the end
# 2 = Bypass standard setup, run custom apps only (Full Simulink Control)
set SIMULINK_MODE 2

PX4_SIM_MODEL=s500

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}

param set-default SIM_GZ_EN 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 100
param set-default SIM_GZ_EC_MIN2 100
param set-default SIM_GZ_EC_MIN3 100
param set-default SIM_GZ_EC_MIN4 100

param set-default SIM_GZ_EC_MAX1 1075.4
param set-default SIM_GZ_EC_MAX2 1075.4
param set-default SIM_GZ_EC_MAX3 1075.4
param set-default SIM_GZ_EC_MAX4 1075.4


# Simulink Guidance Parameters:
param set-default SMG_EN 1
param set-default SMG_OUT_TYPE 2
param set-default SMG_TRAJ_DIR 0

param set-default SDLOG_PROFILE 4097


# Hover Thrust (Crucial for Land Detector)
# Set this to the exact expected hover throttle of your real vehicle (0.0 to 1.0)
#  * @unit norm
#  * @min 0.1
#  * @max 0.8
#  * @decimal 2
#  * @increment 0.01
param set-default MPC_THR_HOVER 0.375

# Data Link Loss Failsafe Action
#  * @value 0 Disabled
#  * @value 1 Hold mode
#  * @value 2 Return mode
#  * @value 3 Land mode
#  * @value 5 Terminate
#  * @value 6 Disarm
param set-default NAV_DLL_ACT 0


# RC Link Loss Failsafe Action
#  * @value 1 Hold mode
#  * @value 2 Return mode
#  * @value 3 Land mode
#  * @value 5 Terminate
#  * @value 6 Disarm
param set-default NAV_RCL_ACT 0


# Force PX4 to execute a full, permanent Flight Termination
# when an emergency kill command is received from the GCS or an RC switch.
# Sets value in seconds to disarm after kill switch/termination is active
param set-default COM_KILL_DISARM 0
